enum WindowAction: String {
    case leftHalf       = "Left Half"
    case rightHalf      = "Right Half"
    case topHalf        = "Top Half"
    case bottomHalf     = "Bottom Half"
    case topLeft        = "Top Left"
    case topRight       = "Top Right"
    case bottomLeft     = "Bottom Left"
    case bottomRight    = "Bottom Right"
    case maximize       = "Maximize"
    case center         = "Center"
    case firstThird      = "First Third"
    case centerThird     = "Center Third"
    case lastThird       = "Last Third"
    case leftTwoThirds   = "Left Two Thirds"
    case rightTwoThirds  = "Right Two Thirds"
}
